package org.cherrypick.picker.shared.errors

enum class ErrorCode {
    DOCUMENT_NOT_FOUND,
    INVALID_DOCUMENT_ID,
    INVALID_DOCUMENT_TITLE,
    INVALID_DOCUMENT_CONTENT,
    INVALID_SOURCE_ID,
    INVALID_INGEST_PAYLOAD,
    UNSUPPORTED_SOURCE_FORMAT,
    REVIEW_TASK_NOT_FOUND,
}
